basePath: /api/v1
definitions:
  bzhspback_fr_breizhsport_internal_dto.BrandResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  bzhspback_fr_breizhsport_internal_dto.CategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  bzhspback_fr_breizhsport_internal_dto.ProductResponse:
    properties:
      brand:
        $ref: '#/definitions/bzhspback_fr_breizhsport_internal_dto.BrandResponse'
      category:
        $ref: '#/definitions/bzhspback_fr_breizhsport_internal_dto.CategoryResponse'
      colors:
        type: string
      description:
        type: string
      discount:
        type: number
      id:
        type: integer
      picture_url:
        type: string
      price:
        type: number
      sizes:
        type: string
      title:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: support@breizhsport.fr
    name: API Support
    url: http://www.breizhsport.fr/support
  description: This is the product service API for BreizhSport e-commerce platform
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BreizhSport Product Service API
  version: "1.0"
paths:
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bzhspback_fr_breizhsport_internal_dto.ProductResponse'
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Get product by ID
      tags:
      - products
  /products/category/{category_id}:
    get:
      consumes:
      - application/json
      description: Retrieves all products for a specific category with optional filters
      parameters:
      - description: Category ID
        in: path
        name: category_id
        required: true
        type: integer
      - description: Brand IDs (comma-separated)
        in: query
        name: brand
        type: string
      - description: Minimum price
        in: query
        name: min_price
        type: number
      - description: Maximum price
        in: query
        name: max_price
        type: number
      - description: Colors (comma-separated)
        in: query
        name: colors
        type: string
      - description: Sizes (comma-separated)
        in: query
        name: sizes
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/bzhspback_fr_breizhsport_internal_dto.ProductResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Get products by category ID
      tags:
      - products
  /products/recommended:
    get:
      consumes:
      - application/json
      description: Retrieves a list of recommended products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/bzhspback_fr_breizhsport_internal_dto.ProductResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Get recommended products
      tags:
      - products
  /products/search:
    get:
      consumes:
      - application/json
      description: Search products by name or description with optional filters
      parameters:
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      - description: Category ID
        in: query
        name: category
        type: integer
      - description: Brand IDs (comma-separated)
        in: query
        name: brand
        type: string
      - description: Minimum price
        in: query
        name: min_price
        type: number
      - description: Maximum price
        in: query
        name: max_price
        type: number
      - description: Colors (comma-separated)
        in: query
        name: colors
        type: string
      - description: Sizes (comma-separated)
        in: query
        name: sizes
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/bzhspback_fr_breizhsport_internal_dto.ProductResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            properties:
              error:
                type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            properties:
              error:
                type: string
            type: object
      summary: Search products
      tags:
      - products
swagger: "2.0"
